### PR TITLE
adding donors list in project.html

### PR DESCRIPTION
**Pull request by click-ripple**
addition of donors list in project.html page

### CODE REVIEW

**Comment by noahsark769** [comment]
@click-ripple: there are now two "donors" headings, which is redundant. This is really the sort of thing you need to be proactive about when checking to make sure that the styles work they way they're supposed to - instead of committing code with two heading, make the decision to take one out and note that you've done so in the pull request.

For now, please remove the blue heading (the higher up one).

screen shot 2016-08-01 at 12 02 48 am

Thanks!

**Comment by click-ripple** [comment]
**@noahsark769**  

Like in this screenshot, there is a donors button and tabs occur whose name is same as the donation level name like basic, gold and silver and that is static.

But as now, the donation levels comes from python code and there is not defined any specific name for donation level like basic, silver or gold that's why the static donors tab is shown.

donrs_project

**Comment by click-ripple** [comment]
**@noahsark769** :  I have removed the donors heading. please check and let me know.
Thanks

**Comment by noahsark769** [comment]
@click-ripple that makes a lot of sense, thanks for taking care of this. The issue of the silver/gold/basic donation levels is really an issue of the design not agreeing with the implementation, which I'm sorry you had to deal with.

At any rate, I'll merge and deploy this now. Thanks again!

**Pull request merged**
