### PR TITLE
Add docker dev support

### PR DESCRIPTION
**Pull request by jayrbolton**
Here are my attempts to get either Docker or Vagrant working, but I have problems starting the app that maybe @harshaddevale-tudip can help me with?

After installing everything in `requirements/dev.txt`, when I run `python manage.py migrate`, then it gives me this error:

```
    default: Traceback (most recent call last):
    default:   File "manage.py", line 14, in <module>
    default:
    default: execute_from_command_line(sys.argv)
    default:   File "/vagrant/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    default:
    default: utility.execute()
    default:   File "/vagrant/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    default:
    default: django.setup()
    default:   File "/vagrant/venv/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    default:
    default: apps.populate(settings.INSTALLED_APPS)
    default:   File "/vagrant/venv/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    default:
    default: app_config.import_models(all_models)
    default:   File "/vagrant/venv/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    default:
    default: self.models_module = import_module(models_module_name)
    default:   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    default:
    default: __import__(name)
    default:   File "/vagrant/venv/local/lib/python2.7/site-packages/taggit/models.py", line 195, in <module>
    default:
    default: class GenericUUIDTaggedItemBase(CommonGenericTaggedItemBase):
    default:   File "/vagrant/venv/local/lib/python2.7/site-packages/taggit/models.py", line 196, in GenericUUIDTaggedItemBase
    default:
    default: object_id = models.UUIDField(verbose_name=_('Object id'), db_index=True)
    default: AttributeError
    default: :
    default: 'module' object has no attribute 'UUIDField'
```

It seems like this is a problem with Django 1.7 and some dependencies? I'm not sure.

### CODE REVIEW

**Comment by noahsark769** [comment]
Looks like we're using django-taggit, which has supported only Django 1.8+ for the past year: https://github.com/alex/django-taggit/commit/acdb9f2f4f263463452161955c48a7306aed413d

UUIDField was introduced in Django 1.8, so if we're still on 1.7 that's probably the issue: https://docs.djangoproject.com/en/1.8/ref/models/fields/

I don't see django-taggit in dev.txt but it looks like it's pinned to 0.12.0 in production.txt: https://github.com/RE-volv/revolv/blob/master/requirements/production.txt#L4

Seems like the preferrable options here would be to either (1) update to Django 1.8 or higher or (2) pin taggit to a 0.12.0 in dev

**Comment by jayrbolton** [comment]
Thanks for the reply. Updating django to 1.8.18 gave an error in django-facebook, which looks like it needs to be updated as well. Not sure if I want to go down that rabbit hole just to get the app running.

It looks like pinning django-taggit to 0.12.0 in dev is the ticket. Thanks for the suggestion. Now I just need more env vars -- MAILCHIMP_API_KEY is the first one that throws an exception. Someone can email me at jayrbolton@protonmail.com with the keys. No rush. Also, this is my pgp pubkey if you want to use that: http://pgp.mit.edu/pks/lookup?op=vindex&search=0xE0E2B8164B87DC2D

**Comment by noahsark769** [comment]
@harshaddevale-tudip - can you give @jayrbolton that key? It's also worth noting that if we don't have that key, we probably shouldn't fail to start the app, just log a warning or something.

**Comment by harshaddevale-tudip** [comment]
@jayrbolton, I have emailed all development environment variable keys to you.

**Pull request closed without merging**
